// Package domain holds the Source entity, its repository port, and its typed domain errors.
package domain

import (
	"context"
	"time"

	"sre-kit/internal/platform/apierror"
)

// Status values for Source.LastStatus, per docs/SPEC.md §3.
const (
	StatusOK          = "ok"
	StatusUnreachable = "unreachable"
	StatusError       = "error"
)

// Source is a configured adapter instance — which adapter, its config, enabled state, and last
// observed status. ID is always a UUID generated by the core at creation time, never derived from
// adapter config (docs/SPEC.md §4), so historical attribution survives a host/IP change.
type Source struct {
	ID          string
	AdapterName string
	ConfigJSON  string
	Enabled     bool
	LastStatus  string
	LastSeenAt  *time.Time
}

// ErrNotFound is returned when a lookup by ID finds no matching source.
var ErrNotFound = apierror.NotFound("source not found")

// Repository is the persistence port for Source, implemented by internal/sources/infrastructure.
type Repository interface {
	Create(ctx context.Context, source Source) error
	Update(ctx context.Context, source Source) error
	Get(ctx context.Context, id string) (Source, error)
	List(ctx context.Context) ([]Source, error)
	Delete(ctx context.Context, id string) error
}
